
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.VButtonBox vbuttonbox1;

	private global::Gtk.Button buttonDodajFolder;

	private global::Gtk.Button buttonListaFoldera;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label1;

	private global::Gtk.ComboBox combobox4;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.HButtonBox hbuttonbox1;

	private global::Gtk.Button buttonOtvori;

	private global::Gtk.Button buttonIzbrisi;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("PDF-Sorter");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(15));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonDodajFolder = new global::Gtk.Button();
		this.buttonDodajFolder.CanFocus = true;
		this.buttonDodajFolder.Name = "buttonDodajFolder";
		this.buttonDodajFolder.UseUnderline = true;
		this.buttonDodajFolder.Label = global::Mono.Unix.Catalog.GetString("Dodaj Folder");
		this.vbuttonbox1.Add(this.buttonDodajFolder);
		global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.buttonDodajFolder]));
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonListaFoldera = new global::Gtk.Button();
		this.buttonListaFoldera.CanFocus = true;
		this.buttonListaFoldera.Name = "buttonListaFoldera";
		this.buttonListaFoldera.UseUnderline = true;
		this.buttonListaFoldera.Label = global::Mono.Unix.Catalog.GetString("Lista Foldera");
		this.vbuttonbox1.Add(this.buttonListaFoldera);
		global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.buttonListaFoldera]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.hbox1.Add(this.vbuttonbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Sortiraj:");
		this.hbox2.Add(this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.combobox4 = global::Gtk.ComboBox.NewText();
		this.combobox4.AppendText(global::Mono.Unix.Catalog.GetString("Abecedno (uzlazno)"));
		this.combobox4.AppendText(global::Mono.Unix.Catalog.GetString("Abecedno (silazno)"));
		this.combobox4.Name = "combobox4";
		this.hbox2.Add(this.combobox4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.combobox4]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow.Add(this.nodeview1);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w8.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox();
		this.hbuttonbox1.Name = "hbuttonbox1";
		this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonOtvori = new global::Gtk.Button();
		this.buttonOtvori.CanFocus = true;
		this.buttonOtvori.Name = "buttonOtvori";
		this.buttonOtvori.UseUnderline = true;
		this.buttonOtvori.Label = global::Mono.Unix.Catalog.GetString("Otvori");
		this.hbuttonbox1.Add(this.buttonOtvori);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.buttonOtvori]));
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonIzbrisi = new global::Gtk.Button();
		this.buttonIzbrisi.CanFocus = true;
		this.buttonIzbrisi.Name = "buttonIzbrisi";
		this.buttonIzbrisi.UseUnderline = true;
		this.buttonIzbrisi.Label = global::Mono.Unix.Catalog.GetString("Izbriši Pdf");
		this.hbuttonbox1.Add(this.buttonIzbrisi);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.buttonIzbrisi]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add(this.hbuttonbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w12.Position = 1;
		this.Add(this.hbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
