
// This file has been generated by the GUI designer. Do not modify.
namespace projektPdf
{
	public partial class WindowUnosPDF
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label5;

		private global::Gtk.Label nazivLabela;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label6;

		private global::Gtk.Label putanjaLabela;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.Button dodajNovuKatButton;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Button odustaniButton;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button spremiButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget projektPdf.WindowUnosPDF
			this.Name = "projektPdf.WindowUnosPDF";
			this.Title = global::Mono.Unix.Catalog.GetString("Unos PDF-a");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child projektPdf.WindowUnosPDF.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 14;
			this.vbox6.BorderWidth = ((uint)(6));
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Naziv:    ");
			this.hbox6.Add(this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.nazivLabela = new global::Gtk.Label();
			this.nazivLabela.Name = "nazivLabela";
			this.hbox6.Add(this.nazivLabela);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.nazivLabela]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox7.Add(this.hbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Putanja:");
			this.hbox7.Add(this.label6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.putanjaLabela = new global::Gtk.Label();
			this.putanjaLabela.Name = "putanjaLabela";
			this.hbox7.Add(this.putanjaLabela);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.putanjaLabela]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox7.Add(this.hbox7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox6.Add(this.vbox7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox7]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Kategorija");
			this.hbox4.Add(this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.Name = "combobox1";
			this.hbox4.Add(this.combobox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.combobox1]));
			w9.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.dodajNovuKatButton = new global::Gtk.Button();
			this.dodajNovuKatButton.CanFocus = true;
			this.dodajNovuKatButton.Name = "dodajNovuKatButton";
			this.dodajNovuKatButton.UseUnderline = true;
			this.dodajNovuKatButton.Label = global::Mono.Unix.Catalog.GetString("Dodaj novu");
			this.hbox4.Add(this.dodajNovuKatButton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.dodajNovuKatButton]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox6.Add(this.hbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Tagovi");
			this.hbox5.Add(this.label4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			global::Gtk.Tooltips w13 = new Gtk.Tooltips();
			w13.SetTip(this.textview1, "Unesite pojmove odvojene zarezom", "Unesite pojmove odvojene zarezom");
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add(this.textview1);
			this.hbox5.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.GtkScrolledWindow]));
			w15.Position = 1;
			this.vbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.odustaniButton = new global::Gtk.Button();
			this.odustaniButton.CanFocus = true;
			this.odustaniButton.Name = "odustaniButton";
			this.odustaniButton.UseUnderline = true;
			this.odustaniButton.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox8.Add(this.odustaniButton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.odustaniButton]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox8.Add(this.fixed1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.fixed1]));
			w18.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.spremiButton = new global::Gtk.Button();
			this.spremiButton.CanFocus = true;
			this.spremiButton.Name = "spremiButton";
			this.spremiButton.UseUnderline = true;
			this.spremiButton.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.hbox8.Add(this.spremiButton);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.spremiButton]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox6.Add(this.hbox8);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox8]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
