
// This file has been generated by the GUI designer. Do not modify.
namespace projektPdf
{
	public partial class WindowNovaKategorija
	{
		private global::Gtk.VBox vbox8;

		private global::Gtk.Label label9;

		private global::Gtk.Entry entry1;

		private global::Gtk.Button spremiButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget projektPdf.WindowNovaKategorija
			this.Name = "projektPdf.WindowNovaKategorija";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowNovaKategorija");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child projektPdf.WindowNovaKategorija.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 29;
			this.vbox8.BorderWidth = ((uint)(9));
			// Container child vbox8.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Unos nove kategorije");
			this.vbox8.Add(this.label9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label9]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.vbox8.Add(this.entry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.entry1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.spremiButton = new global::Gtk.Button();
			this.spremiButton.CanFocus = true;
			this.spremiButton.Name = "spremiButton";
			this.spremiButton.UseUnderline = true;
			this.spremiButton.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.vbox8.Add(this.spremiButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.spremiButton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbox8);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 202;
			this.Show();
		}
	}
}
