
// This file has been generated by the GUI designer. Do not modify.
namespace projektPdf
{
	public partial class WindowPregled
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.VBox vbox1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget projektPdf.WindowPregled
			this.Name = "projektPdf.WindowPregled";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowPregled");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child projektPdf.WindowPregled.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			w1.Add(this.vbox1);
			this.scrolledwindow1.Add(w1);
			this.Add(this.scrolledwindow1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 643;
			this.DefaultHeight = 490;
			this.Show();
		}
	}
}
