
// This file has been generated by the GUI designer. Do not modify.
namespace projektPdf
{
	public partial class WindowDodajPDF
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.FileChooserWidget filechooserwidget2;

		private global::Gtk.HButtonBox hbuttonbox2;

		private global::Gtk.Button buttonOdustani;

		private global::Gtk.Button buttonSpremi;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget projektPdf.WindowDodajPDF
			this.Name = "projektPdf.WindowDodajPDF";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowDodajPDF");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(15));
			// Container child projektPdf.WindowDodajPDF.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.filechooserwidget2 = new global::Gtk.FileChooserWidget(((global::Gtk.FileChooserAction)(0)));
			this.filechooserwidget2.Name = "filechooserwidget2";
			this.hbox1.Add(this.filechooserwidget2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.filechooserwidget2]));
			w1.Position = 0;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Spacing = 20;
			this.hbuttonbox2.BorderWidth = ((uint)(2));
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOdustani = new global::Gtk.Button();
			this.buttonOdustani.CanFocus = true;
			this.buttonOdustani.Name = "buttonOdustani";
			this.buttonOdustani.UseUnderline = true;
			this.buttonOdustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbuttonbox2.Add(this.buttonOdustani);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonOdustani]));
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonSpremi = new global::Gtk.Button();
			this.buttonSpremi.CanFocus = true;
			this.buttonSpremi.Name = "buttonSpremi";
			this.buttonSpremi.UseUnderline = true;
			this.buttonSpremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.hbuttonbox2.Add(this.buttonSpremi);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonSpremi]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add(this.hbuttonbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 758;
			this.DefaultHeight = 512;
			this.Show();
		}
	}
}
